# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shisaku1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 750)
        MainWindow.setWhatsThis("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 220, 490, 490))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(510, 220, 490, 490))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(770, 10, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.system_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.system_info.setGeometry(QtCore.QRect(770, 40, 231, 141))
        self.system_info.setObjectName("system_info")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 641, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Hue_max = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.Hue_max.setMouseTracking(False)
        self.Hue_max.setMaximum(255)
        self.Hue_max.setOrientation(QtCore.Qt.Horizontal)
        self.Hue_max.setObjectName("Hue_max")
        self.verticalLayout.addWidget(self.Hue_max)
        self.Hue_min = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.Hue_min.setMaximum(255)
        self.Hue_min.setOrientation(QtCore.Qt.Horizontal)
        self.Hue_min.setObjectName("Hue_min")
        self.verticalLayout.addWidget(self.Hue_min)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 100, 641, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Satuation_max = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.Satuation_max.setMaximum(255)
        self.Satuation_max.setOrientation(QtCore.Qt.Horizontal)
        self.Satuation_max.setObjectName("Satuation_max")
        self.verticalLayout_2.addWidget(self.Satuation_max)
        self.Satuation_min = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.Satuation_min.setMaximum(255)
        self.Satuation_min.setOrientation(QtCore.Qt.Horizontal)
        self.Satuation_min.setObjectName("Satuation_min")
        self.verticalLayout_2.addWidget(self.Satuation_min)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(910, 10, 91, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 190, 231, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 41, 42))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 100, 41, 42))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 41, 42))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 150, 61, 21))
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 170, 641, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Value_max = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.Value_max.setMaximum(255)
        self.Value_max.setOrientation(QtCore.Qt.Horizontal)
        self.Value_max.setObjectName("Value_max")
        self.verticalLayout_3.addWidget(self.Value_max)
        self.Value_min = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.Value_min.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Value_min.setWhatsThis("")
        self.Value_min.setMaximum(255)
        self.Value_min.setProperty("value", 0)
        self.Value_min.setTracking(True)
        self.Value_min.setOrientation(QtCore.Qt.Horizontal)
        self.Value_min.setInvertedAppearance(False)
        self.Value_min.setInvertedControls(False)
        self.Value_min.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Value_min.setTickInterval(5)
        self.Value_min.setObjectName("Value_min")
        self.verticalLayout_3.addWidget(self.Value_min)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(690, 170, 71, 42))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Val_max_value = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.Val_max_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Val_max_value.setObjectName("Val_max_value")
        self.verticalLayout_7.addWidget(self.Val_max_value)
        self.Val_min_value = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.Val_min_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Val_min_value.setObjectName("Val_min_value")
        self.verticalLayout_7.addWidget(self.Val_min_value)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(690, 100, 71, 42))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Sat_max_value = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Sat_max_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Sat_max_value.setObjectName("Sat_max_value")
        self.verticalLayout_8.addWidget(self.Sat_max_value)
        self.Sat_min_value = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Sat_min_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Sat_min_value.setObjectName("Sat_min_value")
        self.verticalLayout_8.addWidget(self.Sat_min_value)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(690, 30, 71, 42))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Hue_max_value = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.Hue_max_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Hue_max_value.setObjectName("Hue_max_value")
        self.verticalLayout_9.addWidget(self.Hue_max_value)
        self.Hue_min_value = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.Hue_min_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Hue_min_value.setObjectName("Hue_min_value")
        self.verticalLayout_9.addWidget(self.Hue_min_value)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOrange = QtWidgets.QAction(MainWindow)
        self.actionOrange.setObjectName("actionOrange")
        self.actionBlue = QtWidgets.QAction(MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionYellow = QtWidgets.QAction(MainWindow)
        self.actionYellow.setObjectName("actionYellow")

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.change_value)
        self.comboBox.activated['QString'].connect(MainWindow.change_object)
        self.pushButton_2.clicked.connect(MainWindow.write_file)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Orange"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Yellow"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "Reflect Setting"))
        self.label.setText(_translate("MainWindow", "max:"))
        self.label_9.setText(_translate("MainWindow", "min:"))
        self.label_6.setText(_translate("MainWindow", "max:"))
        self.label_7.setText(_translate("MainWindow", "min:"))
        self.label_4.setText(_translate("MainWindow", "max:"))
        self.label_5.setText(_translate("MainWindow", "min:"))
        self.label_10.setText(_translate("MainWindow", "Value"))
        self.Val_max_value.setText(_translate("MainWindow", "0"))
        self.Val_min_value.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Satuation"))
        self.label_3.setText(_translate("MainWindow", "Hue"))
        self.Sat_max_value.setText(_translate("MainWindow", "0"))
        self.Sat_min_value.setText(_translate("MainWindow", "0"))
        self.Hue_max_value.setText(_translate("MainWindow", "0"))
        self.Hue_min_value.setText(_translate("MainWindow", "0"))
        self.actionOrange.setText(_translate("MainWindow", "Orange"))
        self.actionBlue.setText(_translate("MainWindow", "Blue"))
        self.actionYellow.setText(_translate("MainWindow", "Yellow"))

